In [ ]:
import pandas as pd

In [2]:
import sys
print(sys.executable)

c:\Users\Kenjo Condez\Downloads\aiovy_flutter_prototype (1)\aiovy\.venv\Scripts\python.exe

In [5]:
tanzania = pd.read_csv("../data/raw/tanzania.csv")

C:\Users\Kenjo Condez\AppData\Local\Temp\ipykernel_15992\2177160467.py:1: DtypeWarning: Columns (166: hemoglobin_check_result_v2, 193: blood_sugar_result_v2, 225: other_abdominal_palpation_v3, 232: hemoglobin_check_result_v3, 259: blood_sugar_result_v3, 291: other_abdominal_palpation_v4, 294: obstetric_ultrasound_scan_result_v4, 298: hemoglobin_check_result_v4, 325: blood_sugar_result_v4, 326: blood_sugar_action_v4, 357: other_abdominal_palpation_v5, 364: hemoglobin_check_result_v5, 391: blood_sugar_result_v5, 426: obstetric_ultrasound_scan_result_v6, 442: urine_analysis_result_v6, 443: urine_analysis_action_v6, 445: syphilis_test_result_v6, 446: syphilis_test_action_v6, 448: blood_grp_check_result_v6, 449: blood_grp_check_action_v6, 451: check_blood_rhesus_factor_result_v6, 452: check_blood_rhesus_factor_action_v6, 457: blood_sugar_result_v6, 458: blood_sugar_action_v6, 492: obstetric_ultrasound_scan_result_v7, 502: hiv_test_result_v7, 503: hiv_test_action_v7, 511: syphilis_test_result_v7, 512: syphilis_test_action_v7, 514: blood_grp_check_result_v7, 515: blood_grp_check_action_v7, 517: check_blood_rhesus_factor_result_v7, 518: check_blood_rhesus_factor_action_v7, 520: malaria_rapid_test_result_v7, 521: malaria_rapid_test_action_v7, 524: blood_sugar_action_v7, 547: body_temperature_v8, 548: respiratory_rate_v8, 549: pulse_rate_v8, 558: obstetric_ultrasound_scan_result_v8, 559: obstetric_ultrasound_scan_action_v8, 563: hemoglobin_check_action_v8, 565: urine_albumin_check_result_v8, 566: urine_albumin_check_action_v8, 568: hiv_test_result_v8, 569: hiv_test_action_v8, 574: urine_analysis_result_v8, 575: urine_analysis_action_v8, 577: syphilis_test_result_v8, 578: syphilis_test_action_v8, 580: blood_grp_check_result_v8, 581: blood_grp_check_action_v8, 583: check_blood_rhesus_factor_result_v8, 584: check_blood_rhesus_factor_action_v8, 586: malaria_rapid_test_result_v8, 587: malaria_rapid_test_action_v8, 609: other_problems_during_pregnancy, 612: haemoglobin_level_v1_p, 630: haemoglobin_level_v2_p, 645: temperature_v2_p) have mixed types. Specify dtype option on import or set low_memory=False.
  tanzania = pd.read_csv("../data/raw/tanzania.csv")

In [6]:
tanzania.shape

(8817, 683)

In [7]:
tanzania.columns.tolist()

['SN',
 'age',
 'no_pregnancy',
 'last_normal_menustration_date',
 'duration_of_pregnancy_weeks_',
 'duaration_of_pregnancy_days_',
 'expected_date_of_delivery',
 'vaginal_bleeding',
 'vaginal_discharge',
 'nausea_and_vomiting',
 'problems_in_current_pregnancy',
 'specify_current_pregnancy_problems',
 'medication_or_other_treatments',
 'number_of_prior_pregnancies_with_live_births',
 'number_of_prior_pregnancies_with_stillbirths',
 'number_of_prior_deliveries',
 'labour_at_term_1',
 'preterm_labour_1',
 'prior_caesarean_delivery',
 'prio_forceps_delivery',
 'prio_vacuum_delivery',
 'number_of_living_children_and_birth_weight',
 'infant_weight_of_4kg_and_above',
 'miscarriages_or_abortions',
 'number_of_miscarriages_or_abortions',
 'bleeding_in_previous_pregnancies',
 'bleeding_in_previous_deliveries',
 'bleeding_in_previous_puerperium',
 'presence_of_hypertension_in_previous_pregnancies',
 'problems_labour_and_puerperium',
 'specify_problems_in_previous_pregnancy_labour_and_puerperium',
 'heart_problems',
 'hypertension',
 'diabetes_mellitus',
 'gestational_diabetes',
 'liver_diseases',
 'hiv',
 'sexually_transmitted_diseases',
 'tuberculosis',
 'history_of_surgery',
 'allergies',
 'specify_allergies',
 'kidney_diseases',
 'height_cm',
 'weight_kg',
 'sickle_cell_or_haematological_disorders',
 'asthma',
 'epilepsy',
 'history_of_trauma_or_accidents',
 'tetanus_immunization',
 'smoking',
 'use_of_drugs',
 'use_of_alcohol',
 'intimate_partner_violence',
 'tobacco_use',
 'exposure_to_second_handsmoke',
 'twin_pregnancy',
 'congenital_malformations',
 'type_of_cognital_malfomation_baby_born_with',
 'any_genetic_disease',
 'previous_contraceptive_history',
 'contraceptive_method_used',
 'recent_contraception_before_pregnancy',
 'visit_number',
 'smoking_v1',
 'alcohol_and_drugs_abuse_v1',
 'intimate_partner_violence_v1',
 'gbv_v1',
 'social_support_v1',
 'tetanus_immunization_status_v1',
 'mother_not_vaccinated_action_v1',
 'folic_v1',
 'iron_and_folic_v1',
 'calcium_v1',
 'check_date_of_first_foetal_movement_v1',
 'date_of_first_foetal_movement_v1',
 'birth_and_emergency_plan_v1',
 'teach_danger_signs_during_gravidity_v1',
 'discuss_sti_and_hiv_aids_v1',
 'provide_long_lasting_v1',
 'give_intermittent_preventive_treatment_of_malaria_in_gravidity_v1',
 'treat_any_problem_observed_v1',
 'indicate_problem_treated_v1',
 'blood_pressure_v1',
 'bp_is_greater_than_140_90_v1',
 'body_temperature_v1',
 'respiratory_rate_v1',
 'pulse_rate_v1',
 'weight_kg_v1',
 'breast_examination_v1',
 'pregnant_week_number_v1',
 'uterine_size_symphysis_fundal_height_v1',
 'abdominal_palpation_v1',
 'other_abdominal_palpation_v1',
 'fetal_auscaltation_v1',
 'pelvic_examination_findings_v1',
 'obstetric_ultrasound_scan_result_v1',
 'obstetric_ultrasound_scan_action_v1',
 'obstetric_ultrasound_scan_v1',
 'hemoglobin_check_v1',
 'hemoglobin_check_result_v1',
 'hemoglobin_check_action_v1',
 'urine_albumin_check_v1',
 'urine_albumin_check_result_v1',
 'urine_albumin_check_action_v1',
 'hiv_test_v1',
 'hiv_test_result_v1',
 'hiv_test_action_v1',
 'urine_glucose_check_v1',
 'urine_glucose_check_result_v1',
 'urine_glucose_check_action_v1',
 'urine_analysis_v1',
 'urine_analysis_result_v1',
 'urine_analysis_action_v1',
 'syphilis_test_v1',
 'syphilis_test_result_v1',
 'syphilis_test_action_v1',
 'check_blood_group_v1',
 'blood_grp_check_result_v1',
 'blood_grp_check_action_v1',
 'check_blood_rhesus_factor_v1',
 'check_blood_rhesus_factor_result_v1',
 'check_blood_rhesus_factor_action_v1',
 'malaria_rapid_test_v1',
 'malaria_rapid_test_result_v1',
 'malaria_rapid_test_action_v1',
 'blood_sugar_v1',
 'blood_sugar_result_v1',
 'blood_sugar_action_v1',
 'visit_number_1',
 'smoking_v2',
 'alcohol_drugs_abuse_v2',
 'intimate_partner_violence_v2',
 'gbv_v2',
 'social_support_v2',
 'tetanus_immunization_status_v2',
 'mother_not_vaccinated_action_v2',
 'folic_v2',
 'iron_and_folic_v2',
 'calcium_v2',
 'check_date_first_foetal_movement_v2',
 'date_of_first_foetal_movement_v2',
 'birth_and_emergency_plan_v2',
 'teach_danger_signs_during_gravidity_v2',
 'discuss_sti_hiv_aid_v2',
 'provide_long_lasting_v2',
 'give_intermittent_and_preventive_treatment_of_malaria_in_gravidity_v2',
 'treat_any_problem_observed_v2',
 'indicate_problem_treated_v2',
 'blood_pressure_v2',
 'bp_is_greater_than_140_90_v2',
 'body_temperature_v2',
 'respiratory_rate_v2',
 'pulse_rate_v2',
 'weight_kg_v2',
 'breast_examination_v2',
 'pregnant_week_number_v2',
 'uterine_size_symphysis_fundal_height_v2',
 'abdominal_palpation_v2',
 'other_abdominal_palpation_v2',
 'fetal_auscaltation_v2',
 'pelvic_examination_findings_v2',
 'obstetric_ultrasound_scan_result_v2',
 'obstetric_ultrasound_scan_action_v2',
 'obstetric_ultrasound_scan_v2',
 'hemoglobin_check_v2',
 'hemoglobin_check_result_v2',
 'hemoglobin_check_action_v2',
 'urine_albumin_check_v2',
 'urine_albumin_check_result_v2',
 'urine_albumin_check_action_v2',
 'hiv_test_v2',
 'hiv_test_result_v2',
 'hiv_test_action_v2',
 'urine_glucose_check_v2',
 'urine_glucose_check_result_v2',
 'urine_glucose_check_action_v2',
 'urine_analysis_v2',
 'urine_analysis_result_v2',
 'urine_analysis_action_v2',
 'syphilis_test_v2',
 'syphilis_test_result_v2',
 'syphilis_test_action_v2',
 'check_blood_group_v2',
 'blood_grp_check_result_v2',
 'blood_grp_check_action_v2',
 'check_blood_rhesus_factor_v2',
 'check_blood_rhesus_factor_result_v2',
 'check_blood_rhesus_factor_action_v2',
 'malaria_rapid_test_v2',
 'malaria_rapid_test_result_v2',
 'malaria_rapid_test_action_v2',
 'blood_sugar_v2',
 'blood_sugar_result_v2',
 'blood_sugar_action_v2',
 'visit_number_2',
 'smoking_v3',
 'alcohol_drugs_abuse_v3',
 'intimate_partner_violence_v3',
 'gbv_v3',
 'social_support_v3',
 'tetanus_immunization_status_v3',
 'mother_not_vaccinated_action_v3',
 'folic_v3',
 'iron_and_folic_v3',
 'calcium_v3',
 'check_date_first_foetal_movement_v3',
 'date_of_first_foetal_movement_v3',
 'birth_and_emergency_plan_v3',
 'teach_danger_signs_during_gravidity_v3',
 'discuss_sti_hiv_aid_v3',
 'provide_long_lasting_v3',
 'give_intermittent_and_preventive_treatment_of_malaria_in_gravidity_v3',
 'treat_any_problem_observed_v3',
 'indicate_problem_treated_v3',
 'blood_pressure_v3',
 'bp_is_greater_than_140_90_v3',
 'body_temperature_v3',
 'respiratory_rate_v3',
 'pulse_rate_v3',
 'weight_kg_v3',
 'breast_examination_v3',
 'pregnant_week_number_v3',
 'uterine_size_symphysis_fundal_height_v3',
 'abdominal_palpation_v3',
 'other_abdominal_palpation_v3',
 'fetal_auscaltation_v3',
 'pelvic_examination_findings_v3',
 'obstetric_ultrasound_scan_result_v3',
 'obstetric_ultrasound_scan_action_v3',
 'obstetric_ultrasound_scan_v3',
 'hemoglobin_check_v3',
 'hemoglobin_check_result_v3',
 'hemoglobin_check_action_v3',
 'urine_albumin_check_v3',
 'urine_albumin_check_result_v3',
 'urine_albumin_check_action_v3',
 'hiv_test_v3',
 'hiv_test_result_v3',
 'hiv_test_action_v3',
 'urine_glucose_check_v3',
 'urine_glucose_check_result_v3',
 'urine_glucose_check_action_v3',
 'urine_analysis_v3',
 'urine_analysis_result_v3',
 'urine_analysis_action_v3',
 'syphilis_test_v3',
 'syphilis_test_result_v3',
 'syphilis_test_action_v3',
 'check_blood_group_v3',
 'blood_grp_check_result_v3',
 'blood_grp_check_action_v3',
 'check_blood_rhesus_factor_v3',
 'check_blood_rhesus_factor_result_v3',
 'check_blood_rhesus_factor_action_v3',
 'malaria_rapid_test_v3',
 'malaria_rapid_test_result_v3',
 'malaria_rapid_test_action_v3',
 'blood_sugar_v3',
 'blood_sugar_result_v3',
 'blood_sugar_action_v3',
 'visit_number_3',
 'smoking_v4',
 'alcohol_drugs_abuse_v4',
 'intimate_partner_violence_v4',
 'gbv_v4',
 'social_support_v4',
 'tetanus_immunization_status_v4',
 'mother_not_vaccinated_action_v4',
 'folic_v4',
 'iron_and_folic_v4',
 'calcium_v4',
 'check_date_first_foetal_movement_v4',
 'date_of_first_foetal_movement_v4',
 'birth_and_emergency_plan_v4',
 'teach_danger_signs_during_gravidity_v4',
 'discuss_sti_hiv_aid_v4',
 'provide_long_lasting_v4',
 'give_intermittent_and_preventive_treatment_of_malaria_in_gravidity_v4',
 'treat_any_problem_observed_v4',
 'indicate_problem_treated_v4',
 'blood_pressure_v4',
 'bp_is_greater_than_140_90_v4',
 'body_temperature_v4',
 'respiratory_rate_v4',
 'pulse_rate_v4',
 'weight_kg_v4',
 'breast_examination_v4',
 'pregnant_week_number_v4',
 'uterine_size_symphysis_fundal_height_v4',
 'abdominal_palpation_v4',
 'other_abdominal_palpation_v4',
 'fetal_auscaltation_v4',
 'pelvic_examination_findings_v4',
 'obstetric_ultrasound_scan_result_v4',
 'obstetric_ultrasound_scan_action_v4',
 'obstetric_ultrasound_scan_v4',
 'hemoglobin_check_v4',
 'hemoglobin_check_result_v4',
 'hemoglobin_check_action_v4',
 'urine_albumin_check_v4',
 'urine_albumin_check_result_v4',
 'urine_albumin_check_action_v4',
 'hiv_test_v4',
 'hiv_test_result_v4',
 'hiv_test_action_v4',
 'urine_glucose_check_v4',
 'urine_glucose_check_result_v4',
 'urine_glucose_check_action_v4',
 'urine_analysis_v4',
 'urine_analysis_result_v4',
 'urine_analysis_action_v4',
 'syphilis_test_v4',
 'syphilis_test_result_v4',
 'syphilis_test_action_v4',
 'check_blood_group_v4',
 'blood_grp_check_result_v4',
 'blood_grp_check_action_v4',
 'check_blood_rhesus_factor_v4',
 'check_blood_rhesus_factor_result_v4',
 'check_blood_rhesus_factor_action_v4',
 'malaria_rapid_test_v4',
 'malaria_rapid_test_result_v4',
 'malaria_rapid_test_action_v4',
 'blood_sugar_v4',
 'blood_sugar_result_v4',
 'blood_sugar_action_v4',
 'visit_number_4',
 'smoking_v5',
 'alcohol_drugs_abuse_v5',
 'intimate_partner_violence_v5',
 'gbv_v5',
 'social_support_v5',
 'tetanus_immunization_status_v5',
 'mother_not_vaccinated_action_v5',
 'folic_v5',
 'iron_and_folic_v5',
 'calcium_v5',
 'check_date_first_foetal_movement_v5',
 'date_of_first_foetal_movement_v5',
 'birth_and_emergency_plan_v5',
 'teach_danger_signs_during_gravidity_v5',
 'discuss_sti_hiv_aid_v5',
 'provide_long_lasting_v5',
 'give_intermittent_and_preventive_treatment_of_malaria_in_gravidity_v5',
 'treat_any_problem_observed_v5',
 'indicate_problem_treated_v5',
 'blood_pressure_v5',
 'bp_is_greater_than_140_90_v5',
 'body_temperature_v5',
 'respiratory_rate_v5',
 'pulse_rate_v5',
 'weight_kg_v5',
 'breast_examination_v5',
 'pregnant_week_number_v5',
 'uterine_size_symphysis_fundal_height_v5',
 'abdominal_palpation_v5',
 'other_abdominal_palpation_v5',
 'fetal_auscaltation_v5',
 'pelvic_examination_findings_v5',
 'obstetric_ultrasound_scan_result_v5',
 'obstetric_ultrasound_scan_action_v5',
 'obstetric_ultrasound_scan_v5',
 'hemoglobin_check_v5',
 'hemoglobin_check_result_v5',
 'hemoglobin_check_action_v5',
 'urine_albumin_check_v5',
 'urine_albumin_check_result_v5',
 'urine_albumin_check_action_v5',
 'hiv_test_v5',
 'hiv_test_result_v5',
 'hiv_test_action_v5',
 'urine_glucose_check_v5',
 'urine_glucose_check_result_v5',
 'urine_glucose_check_action_v5',
 'urine_analysis_v5',
 'urine_analysis_result_v5',
 'urine_analysis_action_v5',
 'syphilis_test_v5',
 'syphilis_test_result_v5',
 'syphilis_test_action_v5',
 'check_blood_group_v5',
 'blood_grp_check_result_v5',
 'blood_grp_check_action_v5',
 'check_blood_rhesus_factor_v5',
 'check_blood_rhesus_factor_result_v5',
 'check_blood_rhesus_factor_action_v5',
 'malaria_rapid_test_v5',
 'malaria_rapid_test_result_v5',
 'malaria_rapid_test_action_v5',
 'blood_sugar_v5',
 'blood_sugar_result_v5',
 'blood_sugar_action_v5',
 'visit_number_5',
 'smoking_v6',
 'alcohol_drugs_abuse_v6',
 'intimate_partner_violence_v6',
 'gbv_v6',
 'social_support_v6',
 'tetanus_immunization_status_v6',
 'mother_not_vaccinated_action_v6',
 'folic_v6',
 'iron_and_folic_v6',
 'calcium_v6',
 'check_date_first_foetal_movement_v6',
 'date_of_first_foetal_movement_v6',
 'birth_and_emergency_plan_v6',
 'teach_danger_signs_during_gravidity_v6',
 'discuss_sti_hiv_aid_v6',
 'provide_long_lasting_v6',
 'give_intermittent_and_preventive_treatment_of_malaria_in_gravidity_v6',
 'treat_any_problem_observed_v6',
 'indicate_problem_treated_v6',
 'blood_pressure_v6',
 'bp_is_greater_than_140_90_v6',
 'body_temperature_v6',
 'respiratory_rate_v6',
 'pulse_rate_v6',
 'weight_kg_v6',
 'breast_examination_v6',
 'pregnant_week_number_v6',
 'uterine_size_symphysis_fundal_height_v6',
 'abdominal_palpation_v6',
 'other_abdominal_palpation_v6',
 'fetal_auscaltation_v6',
 'pelvic_examination_findings_v6',
 'obstetric_ultrasound_scan_result_v6',
 'obstetric_ultrasound_scan_action_v6',
 'obstetric_ultrasound_scan_v6',
 'hemoglobin_check_v6',
 'hemoglobin_check_result_v6',
 'hemoglobin_check_action_v6',
 'urine_albumin_check_v6',
 'urine_albumin_check_result_v6',
 'urine_albumin_check_action_v6',
 'hiv_test_v6',
 'hiv_test_result_v6',
 'hiv_test_action_v6',
 'urine_glucose_check_v6',
 'urine_glucose_check_result_v6',
 'urine_glucose_check_action_v6',
 'urine_analysis_v6',
 'urine_analysis_result_v6',
 'urine_analysis_action_v6',
 'syphilis_test_v6',
 'syphilis_test_result_v6',
 'syphilis_test_action_v6',
 'check_blood_group_v6',
 'blood_grp_check_result_v6',
 'blood_grp_check_action_v6',
 'check_blood_rhesus_factor_v6',
 'check_blood_rhesus_factor_result_v6',
 'check_blood_rhesus_factor_action_v6',
 'malaria_rapid_test_v6',
 'malaria_rapid_test_result_v6',
 'malaria_rapid_test_action_v6',
 'blood_sugar_v6',
 'blood_sugar_result_v6',
 'blood_sugar_action_v6',
 'visit_number_6',
 'smoking_v7',
 'alcohol_drugs_abuse_v7',
 'intimate_partner_violence_v7',
 'gbv_v7',
 'social_support_v7',
 'tetanus_immunization_status_v7',
 'mother_not_vaccinated_action_v7',
 'folic_v7',
 'iron_and_folic_v7',
 'calcium_v7',
 'check_date_first_foetal_movement_v7',
 'date_of_first_foetal_movement_v7',
 'birth_and_emergency_plan_v7',
 'teach_danger_signs_during_gravidity_v7',
 'discuss_sti_hiv_aid_v7',
 'provide_long_lasting_v7',
 'give_intermittent_and_preventive_treatment_of_malaria_in_gravidity_v7',
 'treat_any_problem_observed_v7',
 'indicate_problem_treated_v7',
 'blood_pressure_v7',
 'bp_is_greater_than_140_90_v7',
 'body_temperature_v7',
 'respiratory_rate_v7',
 'pulse_rate_v7',
 'weight_kg_v7',
 'breast_examination_v7',
 'pregnant_week_number_v7',
 'uterine_size_symphysis_fundal_height_v7',
 'abdominal_palpation_v7',
 'other_abdominal_palpation_v7',
 'fetal_auscaltation_v7',
 'pelvic_examination_findings_v7',
 'obstetric_ultrasound_scan_result_v7',
 'obstetric_ultrasound_scan_action_v7',
 'obstetric_ultrasound_scan_v7',
 'hemoglobin_check_v7',
 'hemoglobin_check_result_v7',
 'hemoglobin_check_action_v7',
 'urine_albumin_check_v7',
 'urine_albumin_check_result_v7',
 'urine_albumin_check_action_v7',
 'hiv_test_v7',
 'hiv_test_result_v7',
 'hiv_test_action_v7',
 'urine_glucose_check_v7',
 'urine_glucose_check_result_v7',
 'urine_glucose_check_action_v7',
 'urine_analysis_v7',
 'urine_analysis_result_v7',
 'urine_analysis_action_v7',
 'syphilis_test_v7',
 'syphilis_test_result_v7',
 'syphilis_test_action_v7',
 'check_blood_group_v7',
 'blood_grp_check_result_v7',
 'blood_grp_check_action_v7',
 'check_blood_rhesus_factor_v7',
 'check_blood_rhesus_factor_result_v7',
 'check_blood_rhesus_factor_action_v7',
 'malaria_rapid_test_v7',
 'malaria_rapid_test_result_v7',
 'malaria_rapid_test_action_v7',
 'blood_sugar_v7',
 'blood_sugar_result_v7',
 'blood_sugar_action_v7',
 'visit_number_7',
 'smoking_v8',
 'alcohol_drugs_abuse_v8',
 'intimate_partner_violence_v8',
 'gbv_v8',
 'social_support_v8',
 'tetanus_immunization_status_v8',
 'mother_not_vaccinated_action_v8',
 'folic_v8',
 'iron_and_folic_v8',
 'calcium_v8',
 'check_date_first_foetal_movement_v8',
 'date_of_first_foetal_movement_v8',
 'birth_and_emergency_plan_v8',
 'teach_danger_signs_during_gravidity_v8',
 'discuss_sti_hiv_aid_v8',
 'provide_long_lasting_v8',
 'give_intermittent_and_preventive_treatment_of_malaria_in_gravidity_v8',
 'treat_any_problem_observed_v8',
 'indicate_problem_treated_v8',
 'blood_pressure_v8',
 'bp_is_greater_than_140_90_v8',
 'body_temperature_v8',
 'respiratory_rate_v8',
 'pulse_rate_v8',
 'weight_kg_v8',
 'breast_examination_v8',
 'pregnant_week_number_v8',
 'uterine_size_symphysis_fundal_height_v8',
 'abdominal_palpation_v8',
 'other_abdominal_palpation_v8',
 'fetal_auscaltation_v8',
 'pelvic_examination_findings_v8',
 'obstetric_ultrasound_scan_result_v8',
 'obstetric_ultrasound_scan_action_v8',
 'obstetric_ultrasound_scan_v8',
 'hemoglobin_check_v8',
 'hemoglobin_check_result_v8',
 'hemoglobin_check_action_v8',
 'urine_albumin_check_v8',
 'urine_albumin_check_result_v8',
 'urine_albumin_check_action_v8',
 'hiv_test_v8',
 'hiv_test_result_v8',
 'hiv_test_action_v8',
 'urine_glucose_check_v8',
 'urine_glucose_check_result_v8',
 'urine_glucose_check_action_v8',
 'urine_analysis_v8',
 'urine_analysis_result_v8',
 'urine_analysis_action_v8',
 'syphilis_test_v8',
 'syphilis_test_result_v8',
 'syphilis_test_action_v8',
 'check_blood_group_v8',
 'blood_grp_check_result_v8',
 'blood_grp_check_action_v8',
 'check_blood_rhesus_factor_v8',
 'check_blood_rhesus_factor_result_v8',
 'check_blood_rhesus_factor_action_v8',
 'malaria_rapid_test_v8',
 'malaria_rapid_test_result_v8',
 'malaria_rapid_test_action_v8',
 'blood_sugar_v8',
 'blood_sugar_result_v8',
 'blood_sugar_action_v8',
 'mode_of_delivery',
 'live_births',
 'still_births',
 'labour_at_term',
 'post_term',
 'preterm_labour',
 'twins_delivery',
 'number_of_twins',
 'newborn_birth_weight_kg_',
 'newborn_with_weight_4kg_and_above',
 'gender_of_new_born_child',
 'new_born_with_complication',
 'immunization_status',
 'miscarriages_or_abortions_1',
 'bleeding_during_pregnancy',
 'bleeding_during_delivery',
 'bleeding_after_delivery',
 'total_antenatal_visits',
 'other_problems_during_pregnancy',
 'blood_pressure_v1_1_p',
 'weight_v1_p',
 'haemoglobin_level_v1_p',
 'pv_bleeding_amount_v1_p',
 'uterus_involution_v1_p',
 'uterus_tenderness_v1_p',
 'perineum_v1_p',
 'surgical_wound_v1_p',
 'breast_pain_and_engorgement_v1_p',
 'pmtct_status_v1_p',
 'breastfeeding_status_v1_p',
 'mental_status_v1_p',
 'child_check_v1_p',
 'vaccinated_v1_p',
 'jaundiced_v1_p',
 'dib_v1_p',
 'umbilicus_status_v1_p',
 'temperature_v1_p',
 'blood_pressure_v2_1_p',
 'weight_v2_p',
 'haemoglobin_level_v2_p',
 'pv_bleeding_amount_v2_p',
 'uterus_involution_v2_p',
 'uterus_tenderness_v2_p',
 'perineum_v2_p',
 'surgical_wound_v2_p',
 'breast_pain_and_engorgement_v2_p',
 'pmtct_status_v2_p',
 'breastfeeding_status_v2_p',
 'mental_status_v2_p',
 'child_check_v2_p',
 'vaccinated_v2_p',
 'jaundiced_v2_p',
 'dib_v2_p',
 'umbilicus_status_v2_p',
 'temperature_v2_p',
 'blood_pressure_v3_1_p',
 'weight_v3_p',
 'haemoglobin_level_v3_p',
 'pv_bleeding_amount_v3_p',
 'uterus_involution_v3_p',
 'uterus_tenderness_v3_p',
 'perineum_v3_p',
 'surgical_wound_v3_p',
 'breast_pain_and_engorgement_v3_p',
 'pmtct_status_v3_p',
 'breastfeeding_status_v3_p',
 'mental_status_v3_p',
 'child_check_v3_p',
 'vaccinated_v3_p',
 'jaundiced_v3_p',
 'dib_v3_p',
 'umbilicus_status_v3_p',
 'temperature_v3_p',
 'blood_pressure_v4_1_p',
 'weight_v4_p',
 'haemoglobin_level_v4_p',
 'pv_bleeding_amount_v4_p',
 'uterus_involution_v4_p',
 'uterus_tenderness_v4_p',
 'perineum_v4_p',
 'surgical_wound_v4_p',
 'breast_pain_and_engorgement_v4_p',
 'pmtct_status_v4_p',
 'breastfeeding_status_v4_p',
 'mental_status_v4_p',
 'child_check_v4_p',
 'vaccinated_v4_p',
 'jaundiced_v4_p',
 'dib_v4_p',
 'umbilicus_status_v4_p',
 'temperature_v4_p',
 'Risk']

In [8]:
tanzania.head()

,SN,age,no_pregnancy,last_normal_menustration_date,duration_of_pregnancy_weeks_,duaration_of_pregnancy_days_,expected_date_of_delivery,vaginal_bleeding,vaginal_discharge,nausea_and_vomiting,...,pmtct_status_v4_p,breastfeeding_status_v4_p,mental_status_v4_p,child_check_v4_p,vaccinated_v4_p,jaundiced_v4_p,dib_v4_p,umbilicus_status_v4_p,temperature_v4_p,Risk
0,1,18,1,2/13/2024,19,4,9/10/2024,no,normal,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,high
1,2,18,3,2/14/2024,38,0,9/11/2024,no,normal,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,high
2,3,24,1,2/14/2024,20,4,9/11/2024,no,normal,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,high
3,4,18,3,2/14/2024,21,5,10/11/2024,no,normal,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,high
4,5,20,1,2/14/2024,30,6,10/11/2024,no,normal,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,low

In [37]:
tanzania.isna().sum().sort_values(ascending=False).head(30)

other_abdominal_palpation_v1           8817
other_abdominal_palpation_v8           8817
blood_sugar_result_v8                  8817
blood_sugar_action_v8                  8817
other_abdominal_palpation_v6           8817
other_abdominal_palpation_v2           8817
other_abdominal_palpation_v7           8817
blood_sugar_action_v7                  8816
other_abdominal_palpation_v4           8816
other_abdominal_palpation_v5           8816
blood_sugar_result_v7                  8816
check_blood_rhesus_factor_result_v8    8816
blood_grp_check_action_v8              8816
check_blood_rhesus_factor_action_v8    8816
blood_grp_check_result_v8              8816
other_abdominal_palpation_v3           8815
blood_grp_check_result_v7              8814
blood_grp_check_action_v7              8814
check_blood_rhesus_factor_result_v7    8813
blood_grp_check_action_v6              8813
check_blood_rhesus_factor_action_v6    8813
syphilis_test_action_v8                8813
check_blood_rhesus_factor_action_v7    8813
obstetric_ultrasound_scan_result_v8    8812
urine_analysis_action_v8               8812
malaria_rapid_test_action_v8           8812
check_blood_rhesus_factor_result_v6    8812
syphilis_test_result_v8                8812
malaria_rapid_test_result_v8           8812
urine_albumin_check_action_v8          8811
dtype: int64

In [38]:
tanzania.duplicated().sum()

np.int64(0)

In [39]:
[col for col in tanzania.columns if any(word in str(col).lower() for word in ["risk", "risklevel", "risk_level", "class", "label", "outcome"])]

['Risk']

In [40]:
tanzania.columns[-20:].tolist()

['temperature_v3_p',
 'blood_pressure_v4_1_p',
 'weight_v4_p',
 'haemoglobin_level_v4_p',
 'pv_bleeding_amount_v4_p',
 'uterus_involution_v4_p',
 'uterus_tenderness_v4_p',
 'perineum_v4_p',
 'surgical_wound_v4_p',
 'breast_pain_and_engorgement_v4_p',
 'pmtct_status_v4_p',
 'breastfeeding_status_v4_p',
 'mental_status_v4_p',
 'child_check_v4_p',
 'vaccinated_v4_p',
 'jaundiced_v4_p',
 'dib_v4_p',
 'umbilicus_status_v4_p',
 'temperature_v4_p',
 'Risk']

In [41]:
[c for c in tanzania.columns if "risk" in str(c).lower()]

['Risk']

In [42]:
[c for c in tanzania.columns if any(
    word in str(c).lower()
    for word in ["age", "systolic", "diastolic", "blood", "glucose", "sugar", "temperature", "temp", "heart", "pulse"]
)]

['age',
 'miscarriages_or_abortions',
 'number_of_miscarriages_or_abortions',
 'heart_problems',
 'blood_pressure_v1',
 'body_temperature_v1',
 'pulse_rate_v1',
 'urine_glucose_check_v1',
 'urine_glucose_check_result_v1',
 'urine_glucose_check_action_v1',
 'check_blood_group_v1',
 'blood_grp_check_result_v1',
 'blood_grp_check_action_v1',
 'check_blood_rhesus_factor_v1',
 'check_blood_rhesus_factor_result_v1',
 'check_blood_rhesus_factor_action_v1',
 'blood_sugar_v1',
 'blood_sugar_result_v1',
 'blood_sugar_action_v1',
 'blood_pressure_v2',
 'body_temperature_v2',
 'pulse_rate_v2',
 'urine_glucose_check_v2',
 'urine_glucose_check_result_v2',
 'urine_glucose_check_action_v2',
 'check_blood_group_v2',
 'blood_grp_check_result_v2',
 'blood_grp_check_action_v2',
 'check_blood_rhesus_factor_v2',
 'check_blood_rhesus_factor_result_v2',
 'check_blood_rhesus_factor_action_v2',
 'blood_sugar_v2',
 'blood_sugar_result_v2',
 'blood_sugar_action_v2',
 'blood_pressure_v3',
 'body_temperature_v3',
 'pulse_rate_v3',
 'urine_glucose_check_v3',
 'urine_glucose_check_result_v3',
 'urine_glucose_check_action_v3',
 'check_blood_group_v3',
 'blood_grp_check_result_v3',
 'blood_grp_check_action_v3',
 'check_blood_rhesus_factor_v3',
 'check_blood_rhesus_factor_result_v3',
 'check_blood_rhesus_factor_action_v3',
 'blood_sugar_v3',
 'blood_sugar_result_v3',
 'blood_sugar_action_v3',
 'blood_pressure_v4',
 'body_temperature_v4',
 'pulse_rate_v4',
 'urine_glucose_check_v4',
 'urine_glucose_check_result_v4',
 'urine_glucose_check_action_v4',
 'check_blood_group_v4',
 'blood_grp_check_result_v4',
 'blood_grp_check_action_v4',
 'check_blood_rhesus_factor_v4',
 'check_blood_rhesus_factor_result_v4',
 'check_blood_rhesus_factor_action_v4',
 'blood_sugar_v4',
 'blood_sugar_result_v4',
 'blood_sugar_action_v4',
 'blood_pressure_v5',
 'body_temperature_v5',
 'pulse_rate_v5',
 'urine_glucose_check_v5',
 'urine_glucose_check_result_v5',
 'urine_glucose_check_action_v5',
 'check_blood_group_v5',
 'blood_grp_check_result_v5',
 'blood_grp_check_action_v5',
 'check_blood_rhesus_factor_v5',
 'check_blood_rhesus_factor_result_v5',
 'check_blood_rhesus_factor_action_v5',
 'blood_sugar_v5',
 'blood_sugar_result_v5',
 'blood_sugar_action_v5',
 'blood_pressure_v6',
 'body_temperature_v6',
 'pulse_rate_v6',
 'urine_glucose_check_v6',
 'urine_glucose_check_result_v6',
 'urine_glucose_check_action_v6',
 'check_blood_group_v6',
 'blood_grp_check_result_v6',
 'blood_grp_check_action_v6',
 'check_blood_rhesus_factor_v6',
 'check_blood_rhesus_factor_result_v6',
 'check_blood_rhesus_factor_action_v6',
 'blood_sugar_v6',
 'blood_sugar_result_v6',
 'blood_sugar_action_v6',
 'blood_pressure_v7',
 'body_temperature_v7',
 'pulse_rate_v7',
 'urine_glucose_check_v7',
 'urine_glucose_check_result_v7',
 'urine_glucose_check_action_v7',
 'check_blood_group_v7',
 'blood_grp_check_result_v7',
 'blood_grp_check_action_v7',
 'check_blood_rhesus_factor_v7',
 'check_blood_rhesus_factor_result_v7',
 'check_blood_rhesus_factor_action_v7',
 'blood_sugar_v7',
 'blood_sugar_result_v7',
 'blood_sugar_action_v7',
 'blood_pressure_v8',
 'body_temperature_v8',
 'pulse_rate_v8',
 'urine_glucose_check_v8',
 'urine_glucose_check_result_v8',
 'urine_glucose_check_action_v8',
 'check_blood_group_v8',
 'blood_grp_check_result_v8',
 'blood_grp_check_action_v8',
 'check_blood_rhesus_factor_v8',
 'check_blood_rhesus_factor_result_v8',
 'check_blood_rhesus_factor_action_v8',
 'blood_sugar_v8',
 'blood_sugar_result_v8',
 'blood_sugar_action_v8',
 'miscarriages_or_abortions_1',
 'blood_pressure_v1_1_p',
 'temperature_v1_p',
 'blood_pressure_v2_1_p',
 'temperature_v2_p',
 'blood_pressure_v3_1_p',
 'temperature_v3_p',
 'blood_pressure_v4_1_p',
 'temperature_v4_p']

In [43]:
tanzania.isna().all().sum()

np.int64(7)

In [44]:
tanzania.dtypes.value_counts()

str        612
float64     42
object      15
int64       14
Name: count, dtype: int64

In [45]:
for term in ["age", "systolic", "diastolic", "blood", "glucose", "sugar", "temperature", "heart", "pulse"]:
    matches = [c for c in tanzania.columns if term in str(c).lower()]
    print(f"\n{term.upper()}:")
    print(matches)

AGE:
['age', 'miscarriages_or_abortions', 'number_of_miscarriages_or_abortions', 'miscarriages_or_abortions_1']

SYSTOLIC:
[]

DIASTOLIC:
[]

BLOOD:
['blood_pressure_v1', 'check_blood_group_v1', 'blood_grp_check_result_v1', 'blood_grp_check_action_v1', 'check_blood_rhesus_factor_v1', 'check_blood_rhesus_factor_result_v1', 'check_blood_rhesus_factor_action_v1', 'blood_sugar_v1', 'blood_sugar_result_v1', 'blood_sugar_action_v1', 'blood_pressure_v2', 'check_blood_group_v2', 'blood_grp_check_result_v2', 'blood_grp_check_action_v2', 'check_blood_rhesus_factor_v2', 'check_blood_rhesus_factor_result_v2', 'check_blood_rhesus_factor_action_v2', 'blood_sugar_v2', 'blood_sugar_result_v2', 'blood_sugar_action_v2', 'blood_pressure_v3', 'check_blood_group_v3', 'blood_grp_check_result_v3', 'blood_grp_check_action_v3', 'check_blood_rhesus_factor_v3', 'check_blood_rhesus_factor_result_v3', 'check_blood_rhesus_factor_action_v3', 'blood_sugar_v3', 'blood_sugar_result_v3', 'blood_sugar_action_v3', 'blood_pressure_v4', 'check_blood_group_v4', 'blood_grp_check_result_v4', 'blood_grp_check_action_v4', 'check_blood_rhesus_factor_v4', 'check_blood_rhesus_factor_result_v4', 'check_blood_rhesus_factor_action_v4', 'blood_sugar_v4', 'blood_sugar_result_v4', 'blood_sugar_action_v4', 'blood_pressure_v5', 'check_blood_group_v5', 'blood_grp_check_result_v5', 'blood_grp_check_action_v5', 'check_blood_rhesus_factor_v5', 'check_blood_rhesus_factor_result_v5', 'check_blood_rhesus_factor_action_v5', 'blood_sugar_v5', 'blood_sugar_result_v5', 'blood_sugar_action_v5', 'blood_pressure_v6', 'check_blood_group_v6', 'blood_grp_check_result_v6', 'blood_grp_check_action_v6', 'check_blood_rhesus_factor_v6', 'check_blood_rhesus_factor_result_v6', 'check_blood_rhesus_factor_action_v6', 'blood_sugar_v6', 'blood_sugar_result_v6', 'blood_sugar_action_v6', 'blood_pressure_v7', 'check_blood_group_v7', 'blood_grp_check_result_v7', 'blood_grp_check_action_v7', 'check_blood_rhesus_factor_v7', 'check_blood_rhesus_factor_result_v7', 'check_blood_rhesus_factor_action_v7', 'blood_sugar_v7', 'blood_sugar_result_v7', 'blood_sugar_action_v7', 'blood_pressure_v8', 'check_blood_group_v8', 'blood_grp_check_result_v8', 'blood_grp_check_action_v8', 'check_blood_rhesus_factor_v8', 'check_blood_rhesus_factor_result_v8', 'check_blood_rhesus_factor_action_v8', 'blood_sugar_v8', 'blood_sugar_result_v8', 'blood_sugar_action_v8', 'blood_pressure_v1_1_p', 'blood_pressure_v2_1_p', 'blood_pressure_v3_1_p', 'blood_pressure_v4_1_p']

GLUCOSE:
['urine_glucose_check_v1', 'urine_glucose_check_result_v1', 'urine_glucose_check_action_v1', 'urine_glucose_check_v2', 'urine_glucose_check_result_v2', 'urine_glucose_check_action_v2', 'urine_glucose_check_v3', 'urine_glucose_check_result_v3', 'urine_glucose_check_action_v3', 'urine_glucose_check_v4', 'urine_glucose_check_result_v4', 'urine_glucose_check_action_v4', 'urine_glucose_check_v5', 'urine_glucose_check_result_v5', 'urine_glucose_check_action_v5', 'urine_glucose_check_v6', 'urine_glucose_check_result_v6', 'urine_glucose_check_action_v6', 'urine_glucose_check_v7', 'urine_glucose_check_result_v7', 'urine_glucose_check_action_v7', 'urine_glucose_check_v8', 'urine_glucose_check_result_v8', 'urine_glucose_check_action_v8']

SUGAR:
['blood_sugar_v1', 'blood_sugar_result_v1', 'blood_sugar_action_v1', 'blood_sugar_v2', 'blood_sugar_result_v2', 'blood_sugar_action_v2', 'blood_sugar_v3', 'blood_sugar_result_v3', 'blood_sugar_action_v3', 'blood_sugar_v4', 'blood_sugar_result_v4', 'blood_sugar_action_v4', 'blood_sugar_v5', 'blood_sugar_result_v5', 'blood_sugar_action_v5', 'blood_sugar_v6', 'blood_sugar_result_v6', 'blood_sugar_action_v6', 'blood_sugar_v7', 'blood_sugar_result_v7', 'blood_sugar_action_v7', 'blood_sugar_v8', 'blood_sugar_result_v8', 'blood_sugar_action_v8']

TEMPERATURE:
['body_temperature_v1', 'body_temperature_v2', 'body_temperature_v3', 'body_temperature_v4', 'body_temperature_v5', 'body_temperature_v6', 'body_temperature_v7', 'body_temperature_v8', 'temperature_v1_p', 'temperature_v2_p', 'temperature_v3_p', 'temperature_v4_p']

HEART:
['heart_problems']

PULSE:
['pulse_rate_v1', 'pulse_rate_v2', 'pulse_rate_v3', 'pulse_rate_v4', 'pulse_rate_v5', 'pulse_rate_v6', 'pulse_rate_v7', 'pulse_rate_v8']

In [46]:
tanzania["Risk"].value_counts(dropna=False)

Risk
high    5510
low     3307
Name: count, dtype: int64

In [47]:
tanzania["Risk"].unique()

<StringArray>
['high', 'low']
Length: 2, dtype: str

In [48]:
clinical_candidates = [
    "age",
    "blood_pressure_v1",
    "blood_sugar_v1",
    "body_temperature_v1",
    "pulse_rate_v1",
    "Risk"
]

tanzania[clinical_candidates].head(20)

,age,blood_pressure_v1,blood_sugar_v1,body_temperature_v1,pulse_rate_v1,Risk
0,18,119/65,no,35.8,112,high
1,18,104/68,yes,not_checked,not_checked,high
2,24,104/68,no,not_checked,not_checked,high
3,18,125/65,no,not_checked,99,high
4,20,NaN,NaN,NaN,NaN,low
5,33,110/70,no,37,72,high
6,26,112/70,yes,37,72,low
7,36,112/52,no,not_checked,not_checked,high
8,17,110/70,yes,37,76,high
9,24,105/58,no,37,103,high
10,32,100/60,no,37,72,high
11,31,120/74,yes,37,75,high
12,38,120/70,no,36.5,76,high
13,22,100/60,yes,37,72,low
14,42,95/59,yes,37,16,high
15,32,117/60,no,37,78,high
16,19,100/65,no,37,72,low
17,23,115/70,no,37,74,high
18,36,110/70,yes,37,76,high
19,26,120/70,no,36.6,70,high

In [49]:
tanzania[clinical_candidates].dtypes

age                    int64
blood_pressure_v1        str
blood_sugar_v1           str
body_temperature_v1      str
pulse_rate_v1            str
Risk                     str
dtype: object

In [50]:
tanzania["blood_pressure_v1"].value_counts(dropna=False).head(20)

blood_pressure_v1
110/70         613
100/60         573
120/70         332
112/67         274
110/60         240
113/74         194
115/60         159
120/80         102
100/70          88
114/70          84
113/67          71
not_checked     65
118/75          63
120/60          61
NaN             55
118/60          53
123/78          52
112/62          47
110/72          47
126/61          47
Name: count, dtype: int64

In [51]:
tanzania["body_temperature_v1"].value_counts(dropna=False).head(20)

body_temperature_v1
37             2657
not_checked    2588
36.5            941
36.7            740
36.6            605
36.8            294
36.9            283
36              168
37.1            129
37.2            122
36.4            108
NaN              55
36.3             38
36.2             32
35.9             12
36.1             12
37.5              8
38                6
37.8              6
37.3              4
Name: count, dtype: int64

In [52]:
tanzania["pulse_rate_v1"].value_counts(dropna=False).head(20)

pulse_rate_v1
not_checked    1088
72              722
76              689
68              597
70              485
78              471
74              398
80              385
69              281
92              256
90              228
86              219
83              191
102             180
79              170
63              168
84              168
82              167
73              167
88              161
Name: count, dtype: int64